# Generated by Django 3.1.3 on 2020-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_main_content',
            field=models.JSONField(null=True),
        ),
    ]
