# Generated by Django 3.1.3 on 2020-11-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_transfer_text_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_content',
        ),
    ]
