# Generated by Django 3.1.4 on 2020-12-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_image_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
